blank_issues_enabled: false
contact_links:
  - name: Community
    url: https://discord.gg/Jm4XStx4Pf
    about: Ask questions and share ideas
  - name: Security report
    url: mailto:security@fedpromptly.com
    about: Report vulnerabilities privately
